# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  vmImage: ubuntu-latest


resources:
  repositories:
  - repository: devops-project-samples
    type: github
    endpoint: rakeshworklab
    name: rakeshworklab/devops-project-samples
  - repository: CRUDwithAngular
    type: github
    endpoint: rakeshworklab
    name: rakeshworklab/CRUDwithAngular

#steps:
#- checkout: devops-project-samples
#- checkout: self
#- script: dir $(Build.SourcesDirectory)

parameters:
  #- name: devops-project-samples
    #displayName: devops_project_samples
    #type: string
  - name: CRUDwithAngular
    displayName: CRUDwithAngular
    type: string

stages:
- stage: reposelection
  displayName: selectrepo_Checkout
  jobs:
  - job: Checkout
    steps:
    - checkout: (git://eq('${{ parameters.CRUDwithAngular }}')) #"eq(${{parameters.devops_project_samples}})")
