# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  vmImage: ubuntu-latest


resources:
  repositories:
  - repository: devops_project_samples
    type: github
    endpoint: rakeshworklab
    name: rakeshworklab/devops_project_samples
  - repository: CRUDwithAngular
    type: github
    endpoint: rakeshworklab
    name: rakeshworklab/CRUDwithAngular

#steps:
#- checkout: devops-project-samples
#- checkout: self
#- script: dir $(Build.SourcesDirectory)

#parameters:
  #- name: devops_project_samples
    #displayName: devops_project_samples
    #type: string
  #- name: CRUDwithAngular
    #displayName: CRUDwithAngular
    #type: string

parameters:
  - name: selectrepo
    displayName: selectrepo
    type: string
    values:
      - CRUDwithAngular
      - devops_project_samples

stages:
- stage: reposelection
  displayName: selectrepo_Checkout
  jobs:
  - job: Checkout
    steps:
    - checkout: ${{parameters.selectrepo}}
    - script: dir $(Build.SourcesDirectory)
    - task: PowerShell@2
      inputs:
       targetType: 'inline'
       script: |
            # Write your PowerShell commands here.
      
            Write-Host " rakesh welcomes you
                        $importPath = "powershell"
                        $pattern = "rakesh(.*?)you"
                        $string = Get-Content $importPath
                        $result = [regex]::match($string, $pattern).Groups[1].Value
                        $result"
- stage: powershell
  displayName: powershellscript
  jobs:
    -  job: executepowershell
       steps:
         - powershell: 
         - task: PowerShell@2
           inputs:
             targetType: 'inline'
             script: |
                  # Write your PowerShell commands here.
      
                  Write-Host "Hello World"