# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

resources:
  repositories:
  - repository: devops-project-samples
    type: github
    endpoint: rakeshworklab
    name: MyGitHubOrgOrUser/MyGitHubRepo1
  - repository: CRUDwithAngular
    type: github
    endpoint: rakeshworklab
    name: MyGitHubOrgOrUser/MyGitHubRepo2

steps:
- checkout: MyGitHubRepo1
- checkout: MyBitbucketRepo2

- script: dir $(Build.SourcesDirectory)